application: rational-hydra-634
version: 1
runtime: python27
api_version: 1
threadsafe: true

#default_expiration: "10s"

# [START handlers]

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /.*
  script: main.app
  
# [END handlers]

# [START libraries]

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
# [END libraries]